version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1  # Set DEBUG mode (change as needed)
    command: python manage.py runserver 0.0.0.0:8000
