# Generated by Django 4.2.7 on 2023-11-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('info_request', 'Дозапрос информации'), ('in_rework', 'На доработке'), ('completed', 'Завершена')], default='new', max_length=20)),
            ],
        ),
    ]
